# Generated by Django 3.2 on 2024-07-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240703_1739'),
        ('reviews', '0002_comment'),
    ]

    operations = [
    ]
