# Generated by Django 3.2 on 2024-07-07 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240707_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Символы латинского алфавита, цифры и знак подчёркивания', regex='^[-a-zA-Z0-9_.@-]+$')], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Символы латинского алфавита, цифры и знак подчёркивания', regex='^[-a-zA-Z0-9_.@-]+$')], verbose_name='Слаг'),
        ),
    ]
